### ISSUE TITLE
Problèmes sur le Lab

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/noesya-hugo-theme#4]
- [x] Il manque les soulignements de liens sur la home.
https://lab.noesya.coop

<img width="1050" alt="Capture d’écran 2023-11-01 à 16 14 05" src="https://github.com/noesya/noesya-hugo-theme/assets/2088968/cde40cb3-8801-4afd-ab46-1852181421bb">

- [x] Il y a des soulignements en trop dans l'index

<img width="1414" alt="Capture d’écran 2023-11-01 à 16 16 02" src="https://github.com/noesya/noesya-hugo-theme/assets/2088968/67d45bd1-f9d4-4238-829f-e77bd4c56241">

- [x] Il faut couper en plusieurs les fichiers du thème, c'est le bazar

- [x] Le footer a encore des cas non gérés
![Capture d’écran 2023-11-01 à 16 15 20](https://github.com/noesya/noesya-hugo-theme/assets/2088968/d4e1655b-4fda-4da4-8a6c-bed8c2aafc67)

- [x] Quand on scroll en bas de home et qu'on refresh, on tombe parfois sur une page vide : 
<img width="1792" alt="Capture d’écran 2023-11-01 à 16 22 28" src="https://github.com/noesya/noesya-hugo-theme/assets/2088968/f4470c39-bcae-42df-926d-4499d2eecd21">

- [x] Le dark mode mange les sur-titres
<img width="981" alt="Capture d’écran 2023-11-01 à 18 36 29" src="https://github.com/noesya/noesya-hugo-theme/assets/2088968/175e6594-4f54-4727-8956-47203d45cf9f">
<img width="1072" alt="Capture d’écran 2023-11-01 à 18 36 32" src="https://github.com/noesya/noesya-hugo-theme/assets/2088968/52ed5854-4359-4cb4-8b6f-0130e087222b">

**Comment by Olivia206** [comment]
Je n'ai pas réussi à reproduire le bug de la page blanche à la réactualisation (on pense que c'est un bug dû au js antérieur), le reste est fix

**Comment by arnaudlevy** [comment]
Cool !
@Olivia206 y a encore des trucs de calage pas parfaits.
L'idée, c'est que quand on passe d'une page à l'autre, ça doit être stable.
1. https://lab.noesya.coop/ 
2. https://lab.noesya.coop/publications/rd/ nickel, le titre R&D est au même endroit que "La coopérative..."
3. https://lab.noesya.coop/publications/2023-10-11-linsoutenable-poids-des-videos-quon-ne-regarde-pas/ alors là ça ne va plus, ça remonte, R&D devrait être fixe

Et à l'idéal, le menu est pile aligné verticalement (R&D en face de R&D)

**Comment by arnaudlevy** [comment]
et l'image de partage du lab est le logo noesya, ça marche pas, ça crop

**Comment by arnaudlevy** [comment]
J'ai réparé l'image de partage

**Comment by Olivia206** [comment]
Pour l'affichage de R&D dans le hero c'est bon ! Idem pour l'alignement vertical du menu

**Comment by arnaudlevy** [comment]
C'est nickel !
